In [24]:
#Numpy 기초
#배열 객체인 ndarray 생성하기 (ndarray: N-dimension array)
import numpy as np #Numpy 패키지를 np로 불러옴

#array(): 매개 변수로 사용되는 리스트, 튜플, 배열 형의 데이터를 이용하여 ndarray 객체를 생성한다. 
data = np.array([1, 2, 3 ,4 ,5]) #1차원 배열
print(data)
print(type(data))
print(data.dtype) #각 요소의 data type은 int32 (32비트 정수형)

[1 2 3 4 5]
<class 'numpy.ndarray'>
int32


In [23]:
#2차원 배열 객체 생성하기
import numpy as np

#random,randn():  가우시안 정규 분포를 갖는 랜덤 수를 생성한다.
data = np.random.randn(2,3) #2행 3열 실수형 랜덤 수 발생
print(data) 
print(data.shape) #(행, 열) 출력
print(data.dtype) #각 데이터의 data type이 float64임

[[-0.79751389  0.96995918  0.2019253 ]
 [ 1.21072162  0.9033095  -1.63066289]]
(2, 3)
float64


In [14]:
#ndarray 객체 0으로 초기화하기 (zeros()이용)+(dtype=np.int32로 정수형 만들기)
import numpy as np

data1 = np.zeros(10)#10개의 0.0 요소로 이루어진 배열 가짐. 모두 float형임
print(data1)
print(data1.dtype)
print()

data2 = np.zeros((2, 3))#2행 3열의 0.0으로 초기화된 64비트 실수형 ndarray 객체 생성
print(data2)
print(data2.dtype)
print()

data3 = np.zeros((2, 3), dtype = np.int32)#data2애서 float형을 int형으로 바꿈
print(data3)
print(data3.dtype)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
float64

[[0. 0. 0.]
 [0. 0. 0.]]
float64

[[0 0 0]
 [0 0 0]]
int32


In [17]:
#ndarray 객체 1으로 초기화하기 (ones()이용)+(dtype=np.int32로 정수형 만들기)
import numpy as np
data1 = np.ones(7)#7개의 1.0 요소로 이루어진 배열 가짐. 모두 float형임
print(data1)
print()

data2 = np.ones((3,4), dtype=np.int32)#요소를 모두 정수형으로
print(data2)
print()

[1. 1. 1. 1. 1. 1. 1.]

[[1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]]



In [22]:
#Numpy의 arange() 메소드 (참고: 파이썬의 range메소드랑 똑같아)
import numpy as np

data = np.arange(10,121,10)
print(data)
print('data[2]: ',data[2])
print('data[5:8]: ',data[5:8])

[ 10  20  30  40  50  60  70  80  90 100 110 120]
data[2]:  30
data[5:8]:  [60 70 80]


In [27]:
#2차원 배열의 요소 추출
import numpy as np

data = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10], [11, 12, 13, 14, 15]])
print('data: ', data)
print('data[2][3]: ', data[2][3])
print('data[0][1:]: ', data[0][1:])
print('data[0]: ', data[0])
print('data[1,2]: ', data[1,2])
print()

data:  [[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]]
data[2][3]:  14
data[0][1:]:  [2 3 4 5]
data[0]:  [1 2 3 4 5]
data[1,2]:  8



In [30]:
#ndarray 배열의 산술 연산
import numpy as np

a = np.array([[10, 20, 30, 40], [50, 60, 70, 80], [90, 100, 110, 120]])

b = a*2 #a의 각 요소를 2배로
print(b)

c = a*a #a의 각 요소를 곱해줌
print(c)

print(a>b) #각 요소를 비교

[[ 20  40  60  80]
 [100 120 140 160]
 [180 200 220 240]]
[[  100   400   900  1600]
 [ 2500  3600  4900  6400]
 [ 8100 10000 12100 14400]]
[[False False False False]
 [False False False False]
 [False False False False]]


In [42]:
#배열의 통계 메소드 (sum, mean, max, min, argmax, argmin, axis가 0이면 x축 기준&1이면 y축 기준))
import numpy as np

a = np.array([[10, 5, 35, 70], [90, 100, 23, 80], [27, 100, 28, 52]])
print(a)
print('합계: ', a.sum()) #배열의 모든 요소의 합계
print('평균: ', a.mean()) #배열의 모든 요소의 평균값 반환
print('최댓값: ', a.max()) #배열의 모든 요소 값 중에서 최댓값
print('최솟값', a.min()) #배열의 모든 요소 값 중에서 최솟값
print()

print(a.max(axis=0)) #x축 기준이므로 수직인 열단위로 따짐
print(a.min(axis=1)) #y축 기준이므로 수직인 행단위로 따짐
print()

index1 = np.argmax(a, axis=0)
index2 = np.argmax(a, axis=1)
print(index1, index2)

[[ 10   5  35  70]
 [ 90 100  23  80]
 [ 27 100  28  52]]
합계:  620
평균:  51.666666666666664
최댓값:  100
최솟값 5

[ 90 100  35  80]
[ 5 23 27]

[1 1 0 1] [3 1 1]


In [53]:
#배열에 조건식 사용 (sum(), where(조건식, true일때 값, false일때 값))
import numpy as np

a = np.random.randn(3, 4) #3행 4열 실수형 랜덤 수 발생
print(a,'\n')

print(a>0,'\n') #각 요소가 양수인지 체크

total = (a<0).sum() #sum()은 총 갯수를 의미(더하는거 아님
print(total,'\n')

a2 = np.where(a>0, 7, data) # 조건식이 true일때 7, false일때 data
print(a2,'\n')

[[ 0.30561053 -0.30579309 -1.23105308 -1.01901961]
 [ 1.14969812 -1.02579364 -0.48364043  0.74608716]
 [-1.11298419 -1.01582296 -0.38065325  0.39066609]] 

[[ True False False False]
 [ True False False  True]
 [False False False  True]] 

8 

[[  7  20  30  40]
 [  7  60  70   7]
 [ 90 100 110   7]] 



In [56]:
#배열의 요소 정렬(sort(k): k가 0이면 x축 기준, 1이면 y축 기준)
import numpy as np
a = np.array([[10, 5, 35, 70], [90, 100, 23, 80], [27, 100, 28, 52]])
print(a,'\n')

a.sort(0) #x축 기준이므로, 세로로 정렬
print(a,'\n')

a.sort(1) #y축 기준이므로, 가로로 정렬
print(a,'\n')

[[ 10   5  35  70]
 [ 90 100  23  80]
 [ 27 100  28  52]] 

[[ 10   5  23  52]
 [ 27 100  28  70]
 [ 90 100  35  80]] 

[[  5  10  23  52]
 [ 27  28  70 100]
 [ 35  80  90 100]] 



In [62]:
#배열에 열과 행 삽입 (insert())
import numpy as np

a = np.arange(10) #0~9까지 배열
print('a: ', a)

b = np.insert(a, 3, 10) #a의 인덱스 3의 요소에 10의 값 대입
print('b: ',b)

x = np.array([[1, 1, 1], [2, 2, 2], [3, 3, 3]])
print('x: ', x, '\n')

y = np.insert(x, 1, 10, axis=0) #x배열을 열 방향으로(?) 인덱스 1인 요소에 모든 요소 값이 10인 행을 하나 삽입한다.
print('y: ', y, '\n')

y = np.insert(x, 1, 10, axis=1) #x배열을 행 방향으로(?) 인덱스 1인 요소에 모든 요소 값이 10인 열을 하나 삽입한다.
print('y: ', y, '\n')

a:  [0 1 2 3 4 5 6 7 8 9]
b:  [ 0  1  2 10  3  4  5  6  7  8  9]
x:  [[1 1 1]
 [2 2 2]
 [3 3 3]] 

y:  [[ 1  1  1]
 [10 10 10]
 [ 2  2  2]
 [ 3  3  3]] 

y:  [[ 1 10  1  1]
 [ 2 10  2  2]
 [ 3 10  3  3]] 

