### Numpy Version

In [7]:
import numpy as np

In [9]:
np.__version__

'1.19.2'

### ndarray 생성

In [13]:
arr = np.array([1,2,3,4], dtype=int)

In [17]:
arr

array([1, 2, 3, 4])

In [18]:
type(arr)

numpy.ndarray

In [19]:
arr.shape

(4,)

In [20]:
# 1차원 리스트
myList = [1,2,3,4]   # python List
arr = np.array(myList, dtype=float)

In [21]:
arr

array([1., 2., 3., 4.])

In [22]:
# 퀴즈
myList = [1.3, 2.3, 3.3, 4.3]
arr = np.array(myList, dtype=int)

In [23]:
arr

array([1, 2, 3, 4])

In [24]:
# 2차원 리스트
myList2 = [[1,2,3,4],
           [5,6,7,8]]

In [25]:
myList2

[[1, 2, 3, 4], [5, 6, 7, 8]]

In [26]:
arr = np.array(myList2)

In [27]:
arr.shape

(2, 4)

In [28]:
type(arr)

numpy.ndarray

In [29]:
arr

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [30]:
myList2 = [[1.3,2,3,4],
           [5,6,7,8]]

In [31]:
arr = np.array(myList2)

In [32]:
arr

array([[1.3, 2. , 3. , 4. ],
       [5. , 6. , 7. , 8. ]])

In [44]:
myList = [1, 3.14, 'hello_world','1234']

In [45]:
myList

[1, 3.14, 'hello_world', '1234']

In [48]:
arr = np.array(myList)

In [49]:
arr

array(['1', '3.14', 'hello_world', '1234'], dtype='<U32')

In [50]:
arr[0]+arr[1]

'13.14'

In [51]:
float(arr[0])+float(arr[1])

4.140000000000001

### 슬라이싱(Slicing)

배열을 부분선택

#### 1차원 배열의 부분선택

In [53]:
arr = np.array([0,1,2,3,4,5,6,7,8,9])
arr.shape

(10,)

In [56]:
arr[10]

IndexError: index 10 is out of bounds for axis 0 with size 10

In [57]:
arr[-1]

9

In [58]:
arr[-10]

0

In [59]:
arr[-11]

IndexError: index -11 is out of bounds for axis 0 with size 10

#### 2차원 배열의 부분선택

In [60]:
arr2d = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])

In [61]:
arr2d

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [75]:
# np.arange(12) : 시작값은 0이고(생략), 종료조건이 12미만
# np.arange(1,13) : 시작값이 1이고, 종료조건 13미만
arr2d = np.array(np.arange(1, 13)).reshape(3,4)

In [76]:
arr2d

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [77]:
arr2d[0,2]

3

In [78]:
arr2d[2,2]

11

In [79]:
arr1d = np.array(np.arange(1, 13))

In [80]:
arr1d

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [81]:
# 2~12까지만
# 시작값:종료값(생략하면 끝까지)
arr1d[1:]

array([ 2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [83]:
#시작값(이상):종료값(index미만)
arr1d[1:10]

array([ 2,  3,  4,  5,  6,  7,  8,  9, 10])

In [84]:
arr1d[:-1]

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [85]:
arr1d[:-2]

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [86]:
arr1d[:-3]

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [87]:
#2차원 배열의 범위 지정(슬라이싱)
arr2d = np.array(np.arange(1, 13)).reshape(3,4)

In [88]:
arr2d

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [89]:
# 한 행 지정한 뒤 모두 가져오기
# 행,열(: 모든 열) 
arr2d[1, :]

array([5, 6, 7, 8])

In [90]:
arr2d[1, :].shape

(4,)

In [91]:
arr2d[:,2]

array([ 3,  7, 11])

In [92]:
arr2d[1, :].shape

(4,)

In [93]:
arr2d[:2,1:3]

array([[2, 3],
       [6, 7]])

In [95]:
# 5x5 배열, 1부터 1씩 증가하는 배열 (1~25)
my2dArr = np.array(np.arange(1,26)).reshape(5,5)

In [96]:
my2dArr

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [97]:
my2dArr[2:,1:4]

array([[12, 13, 14],
       [17, 18, 19],
       [22, 23, 24]])

### Fancy Indexing

범위가 아닌 특정 index값을 선택해서 추출하고 싶을 때

In [99]:
# 1차원의 Fancy Indexing
myArr = np.array(np.arange(1,10))

In [100]:
myArr

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [101]:
idx = [0, 2, 4]

In [103]:
myArr[idx]

array([1, 3, 5])

In [104]:
# 2차원의 Fancy Indexing
my2dArr = np.array(np.arange(1,13)).reshape(3,4)
my2dArr

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [107]:
index =[0,2,3]

In [108]:
my2dArr[:2,index]

array([[1, 3, 4],
       [5, 7, 8]])

### Boolean Indexing

조건 필터링을 통해서 Boolean값을 이용한 색인

In [109]:
arr = np.array(np.arange(1,8))

In [110]:
arr

array([1, 2, 3, 4, 5, 6, 7])

In [123]:
arr2d = np.array(np.arange(1,13)).reshape(3,4)

In [124]:
arr2d 

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [136]:
myTrueFalse = [True, False, True, False,  False, False, False]

In [137]:
TrueFalse = np.array(myTrueFalse)

In [138]:
arr[TrueFalse]

array([1, 3])

In [133]:
myTrueFalse = [[True, False, True, False],[True, False, True, False],[False, False, False, False]]

In [134]:
TrueFalse = np.array(myTrueFalse)

In [135]:
arr2d[TrueFalse]

array([1, 3, 5, 7])