### Numpy Version

In [28]:
import numpy as np

In [29]:
np.__version__

'1.18.5'

### ndarray 생성

In [30]:
arr = np.array([1,2,3,4], dtype=int)

In [31]:
arr

array([1, 2, 3, 4])

In [32]:
type(arr)

numpy.ndarray

In [33]:
arr.shape

(4,)

In [34]:
# 1차원 리스트
myList = [1,2,3,4]   # python List
arr = np.array(myList, dtype=float)

In [35]:
arr

array([1., 2., 3., 4.])

In [36]:
# 퀴즈
myList = [1.3, 2.3, 3.3, 4.3]
arr = np.array(myList, dtype=int)

In [37]:
arr

array([1, 2, 3, 4])

In [38]:
# 2차원 리스트
myList2 = [[1,2,3,4],
           [5,6,7,8]]

In [39]:
myList2

[[1, 2, 3, 4], [5, 6, 7, 8]]

In [40]:
arr = np.array(myList2)

In [41]:
arr.shape

(2, 4)

In [42]:
type(arr)

numpy.ndarray

In [43]:
arr

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [44]:
myList2 = [[1.3,2,3,4],
           [5,6,7,8]]

In [45]:
arr = np.array(myList2)

In [46]:
arr

array([[1.3, 2. , 3. , 4. ],
       [5. , 6. , 7. , 8. ]])

In [47]:
myList = [1, 3.14, 'hello_world','1234']

In [48]:
myList

[1, 3.14, 'hello_world', '1234']

In [49]:
arr = np.array(myList)

In [50]:
arr

array(['1', '3.14', 'hello_world', '1234'], dtype='<U32')

In [51]:
arr[0]+arr[1]

'13.14'

In [52]:
float(arr[0])+float(arr[1])

4.140000000000001

### 슬라이싱(Slicing)

배열을 부분선택

#### 1차원 배열의 부분선택

In [53]:
arr = np.array([0,1,2,3,4,5,6,7,8,9])
arr.shape

(10,)

In [54]:
arr[10]

IndexError: index 10 is out of bounds for axis 0 with size 10

In [55]:
arr[-1]

9

In [56]:
arr[-10]

0

In [57]:
arr[-11]

IndexError: index -11 is out of bounds for axis 0 with size 10

#### 2차원 배열의 부분선택

In [58]:
arr2d = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])

In [59]:
arr2d

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [60]:
# np.arange(12) : 시작값은 0이고(생략), 종료조건이 12미만
# np.arange(1,13) : 시작값이 1이고, 종료조건 13미만
arr2d = np.array(np.arange(1, 13)).reshape(3,4)

In [61]:
arr2d

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [62]:
arr2d[0,2]

3

In [63]:
arr2d[2,2]

11

In [64]:
arr1d = np.array(np.arange(1, 13))

In [65]:
arr1d

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [66]:
# 2~12까지만
# 시작값:종료값(생략하면 끝까지)
arr1d[1:]

array([ 2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [67]:
#시작값(이상):종료값(index미만)
arr1d[1:10]

array([ 2,  3,  4,  5,  6,  7,  8,  9, 10])

In [68]:
arr1d[:-1]

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [69]:
arr1d[:-2]

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [70]:
arr1d[:-3]

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [71]:
#2차원 배열의 범위 지정(슬라이싱)
arr2d = np.array(np.arange(1, 13)).reshape(3,4)

In [72]:
arr2d

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [73]:
# 한 행 지정한 뒤 모두 가져오기
# 행,열(: 모든 열) 
arr2d[1, :]

array([5, 6, 7, 8])

In [74]:
arr2d[1, :].shape

(4,)

In [75]:
arr2d[:,2]

array([ 3,  7, 11])

In [76]:
arr2d[1, :].shape

(4,)

In [77]:
arr2d[:2,1:3]

array([[2, 3],
       [6, 7]])

In [78]:
# 5x5 배열, 1부터 1씩 증가하는 배열 (1~25)
my2dArr = np.array(np.arange(1,26)).reshape(5,5)

In [79]:
my2dArr

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [80]:
my2dArr[2:,1:4]

array([[12, 13, 14],
       [17, 18, 19],
       [22, 23, 24]])

### Fancy Indexing

범위가 아닌 특정 index값을 선택해서 추출하고 싶을 때

In [81]:
# 1차원의 Fancy Indexing
myArr = np.array(np.arange(1,10))

In [82]:
myArr

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [83]:
idx = [0, 2, 4]

In [84]:
myArr[idx]

array([1, 3, 5])

In [85]:
# 2차원의 Fancy Indexing
my2dArr = np.array(np.arange(1,13)).reshape(3,4)
my2dArr

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [86]:
index =[0,2,3]

In [87]:
my2dArr[:2,index]

array([[1, 3, 4],
       [5, 7, 8]])

### Boolean Indexing

조건 필터링을 통해서 Boolean값을 이용한 색인

In [88]:
arr = np.array(np.arange(1,8))

In [89]:
arr

array([1, 2, 3, 4, 5, 6, 7])

In [90]:
arr2d = np.array(np.arange(1,13)).reshape(3,4)

In [91]:
arr2d 

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [92]:
myTrueFalse = [True, False, True, False,  False, False, False]

In [93]:
TrueFalse = np.array(myTrueFalse)

In [94]:
arr[TrueFalse]

array([1, 3])

In [95]:
myTrueFalse = [[True, False, True, False],[True, False, True, False],[False, False, False, False]]

In [96]:
TrueFalse = np.array(myTrueFalse)

In [97]:
arr2d[TrueFalse]

array([1, 3, 5, 7])

In [98]:
arr2d

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [99]:
# 조건 필터
TrueFalse = arr2d > 2

In [100]:
TrueFalse

array([[False, False,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True]])

In [101]:
arr2d[TrueFalse]

array([ 3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [102]:
arr2d[arr2d > 2]

array([ 3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [103]:
arr2d[arr2d <5]

array([1, 2, 3, 4])

### arange란?

array + range = arange

In [104]:
arr = [1,2,3,4,5,6,7,8,9,10]

In [105]:
# start(이상), stop(미만)
arr = np.arange(1,11)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [106]:
#키워드를 사용해서 순서 없이
arr = np.arange(start=1, stop=111)
arr

array([  1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,  13,
        14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,  26,
        27,  28,  29,  30,  31,  32,  33,  34,  35,  36,  37,  38,  39,
        40,  41,  42,  43,  44,  45,  46,  47,  48,  49,  50,  51,  52,
        53,  54,  55,  56,  57,  58,  59,  60,  61,  62,  63,  64,  65,
        66,  67,  68,  69,  70,  71,  72,  73,  74,  75,  76,  77,  78,
        79,  80,  81,  82,  83,  84,  85,  86,  87,  88,  89,  90,  91,
        92,  93,  94,  95,  96,  97,  98,  99, 100, 101, 102, 103, 104,
       105, 106, 107, 108, 109, 110])

In [107]:
# (start, stop, step)
# 홀수만 생성
arr = np.arange(1,11,2)
arr

array([1, 3, 5, 7, 9])

In [108]:
arr = np.arange(start=1, step=2, stop=11)
arr

array([1, 3, 5, 7, 9])

### range (numpy와는 상관없는 python문법)

In [109]:
# range는 조건을 말할뿐 아직 숫자가 생성 X
test = range(1,11)
print(test)

range(1, 11)


In [110]:
for i in range(1,11):
    print(i)

1
2
3
4
5
6
7
8
9
10


In [111]:
for i in range(1,11,2):
    print(i)

1
3
5
7
9


### 1차원 정렬

In [112]:
arr = np.array([1,10,5,8,2,4,3,6,7,9])

In [113]:
arr

array([ 1, 10,  5,  8,  2,  4,  3,  6,  7,  9])

In [114]:
mySort = np.sort(arr)

In [115]:
mySort

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [116]:
# 내림차순 정렬일 경우 옵션값에 -1을 지정한다.
np.sort(arr)[::-1]

array([10,  9,  8,  7,  6,  5,  4,  3,  2,  1])

### 2차원 정렬

In [117]:
arr2d = np.array([[5,6,7,8],
                [4,3,2,1],
                [10,9,12,11]])

In [118]:
arr2d.shape

(3, 4)

In [119]:
arr2d

array([[ 5,  6,  7,  8],
       [ 4,  3,  2,  1],
       [10,  9, 12, 11]])

In [120]:
# axis는 축이 행인지, 열인지를 가리킨다.
# axis=1하면 같은 행안에서 정렬이 된다.
np.sort(arr2d, axis=1)

array([[ 5,  6,  7,  8],
       [ 1,  2,  3,  4],
       [ 9, 10, 11, 12]])

In [121]:
arr2d

array([[ 5,  6,  7,  8],
       [ 4,  3,  2,  1],
       [10,  9, 12, 11]])

In [122]:
# axis=0이면 같은 열끼리 비교하고 정렬된다.
np.sort(arr2d, axis=0)

array([[ 4,  3,  2,  1],
       [ 5,  6,  7,  8],
       [10,  9, 12, 11]])

### index를 반환하는 argsort

In [123]:
arr2d = np.array([[5,6,7,8],
                [4,3,2,1],
                [10,9,12,11]])

In [124]:
arr2d

array([[ 5,  6,  7,  8],
       [ 4,  3,  2,  1],
       [10,  9, 12, 11]])

In [125]:
#열 정렬(왼쪽에서 오른쪽으로)
# argsort를 통해 출력되는 배열의 데이터는 index값을 의미
np.argsort(arr2d, axis=1)

array([[0, 1, 2, 3],
       [3, 2, 1, 0],
       [1, 0, 3, 2]], dtype=int64)

### numpy를 이용한 행렬 연산

In [126]:
# 행렬의 덧셈
a = np.array([[1,2,3],
              [2,3,4]])

In [127]:
b = np.array([[3,4,5],
              [1,2,3]])

In [128]:
a+b

array([[4, 6, 8],
       [3, 5, 7]])

In [129]:
a = np.array([[1,2,3],
              [2,3,4]])

In [130]:
b = np.array([[1,2],
              [3,4],
              [5,6]])

In [131]:
a+b

ValueError: operands could not be broadcast together with shapes (2,3) (3,2) 

In [132]:
# np.sum
a = np.array(np.arange(1,26)).reshape(5,5)
a

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [133]:
# 같은 열데이터 간 더하기 
np.sum(a,axis=0)

array([55, 60, 65, 70, 75])

In [134]:
# 같은 행데이터 간 더하기
np.sum(a,axis=1)

array([ 15,  40,  65,  90, 115])

In [135]:
# 행렬의 뺄셈은 생략

In [136]:
# 행렬의 곱셈
a = np.array([[1,2,3],
              [2,3,4]])

In [137]:
b = np.array([[3,4,5],
              [1,2,3]])

In [138]:
a.shape, b.shape

((2, 3), (2, 3))

In [139]:
# 아다마르 곱
a*b

array([[ 3,  8, 15],
       [ 2,  6, 12]])

In [140]:
a = np.array(np.arange(1,10)).reshape(3,3)
a

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [141]:
b = np.array(np.arange(1,7)).reshape(3,2)
b

array([[1, 2],
       [3, 4],
       [5, 6]])

In [142]:
a.shape, b.shape

((3, 3), (3, 2))

In [143]:
# 행렬의 곱셈 표현1
np.dot(a,b)

array([[ 22,  28],
       [ 49,  64],
       [ 76, 100]])

In [144]:
# 행렬의 곱셈 표현2
a.dot(b)

array([[ 22,  28],
       [ 49,  64],
       [ 76, 100]])

### Broadcasting

In [145]:
a = np.array([[1,2,3],
              [2,3,4]])

In [146]:
b = np.array([[3,3,3],
              [3,3,3]])

In [147]:
a + b

array([[4, 5, 6],
       [5, 6, 7]])

In [148]:
# broadcasting 연산
a + 3

array([[4, 5, 6],
       [5, 6, 7]])

In [149]:
a - 3

array([[-2, -1,  0],
       [-1,  0,  1]])

In [150]:
# 아다마르 곱
a * 3

array([[ 3,  6,  9],
       [ 6,  9, 12]])

In [151]:
a / 3

array([[0.33333333, 0.66666667, 1.        ],
       [0.66666667, 1.        , 1.33333333]])

In [152]:
a

array([[1, 2, 3],
       [2, 3, 4]])

In [153]:
b = np.array([[1],
             [2]])

In [154]:
a.shape, b.shape

((2, 3), (2, 1))

In [155]:
# 행단위로 broadcasting연산
a * b

array([[1, 2, 3],
       [4, 6, 8]])

In [156]:
a

array([[1, 2, 3],
       [2, 3, 4]])

In [157]:
# 열 단위로 broadcasting연산
b = np.array([1,2,3])

In [158]:
a*b

array([[ 1,  4,  9],
       [ 2,  6, 12]])